[hooks]
postinstall = [
  "{% set is_in_ci = get_env(name='CI', default='') %}{% if is_in_ci %}echo 'Not setting up git hooks as mise is running in CI!'{% else %}prek install -f -c .config/prek.toml{% endif %}",
]

[settings]
experimental = true # Needed for hooks as of v2025.6.2
windows_default_inline_shell_args = "powershell.exe /c"

[tasks.copier-update]
run = "copier update --answers-file .config/copier-answers.yml --skip-answered --trust"

[tasks.docs-server]
run = "zensical serve -f .config/zensical.toml"

[tasks.test]
run = '''
prek run -c .config/prek.toml --all-files
copier copy --trust --vcs-ref=HEAD --pretend -d 'repo_name=render-test' -d 'author_name=Name' -d 'repo_setup_actions=None' -d 'developer_platform=GitHub' -d 'github_username=username' -d 'github_org=' -d 'project_description=Rendering Test' -d 'project_type=Template' -d 'project_name=Rendering Test' -d 'project_visibility=Public' -d 'license=MIT' -d 'zensical_target=docs_site Directory in Repo' -d 'lifecycle=Pre-Alpha' . fake-path
'''

[tasks.integration-test-gh]
run = '''
copier copy --trust --vcs-ref={{option(name="branch",default="HEAD")}} -d 'developer_platform=GitHub' -d 'project_description=Integration Test - NOT FOR PUBLIC USE' -d 'project_type=Template' -d 'project_name=Integration Test' -d 'project_visibility=Public' -d 'license=MIT' -d 'lifecycle=Pre-Alpha' https://github.com/natescherer/postmodern-repo-copiertemplate {{option(name="path")}}
'''

[tasks.integration-test-azdo]
run = '''
copier copy --trust --vcs-ref={{option(name="branch",default="HEAD")}} -d 'developer_platform=Azure DevOps' -d 'project_description=Integration Test - NOT FOR PUBLIC USE' -d 'project_type=Template' -d 'project_name=Integration Test' -d 'project_visibility=Private' -d 'license=None' -d 'lifecycle=Pre-Alpha' https://github.com/natescherer/postmodern-repo-copiertemplate {{option(name="path")}}
'''

[tools]
# Backends
python = "3.14.3" # Used by copier
# Tools
actionlint = "1.7.11"
"aqua:crate-ci/typos" = "1.44.0"
"aqua:j178/prek" = "0.3.8"
"aqua:tombi-toml/tombi" = "0.9.14"
committed = "1.1.10"
ruff = "0.15.8"
rumdl = "0.1.66"
shellcheck = "0.10.0"
uv = "0.11.3" # Used by pipx tools
yamlfmt = "0.20.0"

[tools."pipx:copier"]
version = "9.14.1"
uvx_args = "--with copier-template-extensions==0.3.3 --with jinja2-shell-extension==2.1.1"

[tools."pipx:invoke"]
version = "3.0.2"
uvx_args = "--with copier==9.14.1 --with githubkit==0.15.2 --with requests==2.33.1 --with rich==14.3.3"

[tools."pipx:zensical"]
version = "0.0.31"
uvx_args = "--with git+https://github.com/squidfunk/mike.git@2.2.0+zensical-0.1.0"
