name: $(BuildId)

trigger:
  branches:
    exclude:
      - "*"

schedules:
  # Matches maint-copier_update_check.yml's own schedule (5pm UTC every Monday).
  - cron: 0 17 * * 1
    displayName: Check for Copier Template Updates Every Monday at 5pm UTC
    branches:
      include:
        - main

variables:
  CI: true
  MISE_ENV: ci

pool:
  vmImage: ubuntu-latest

stages:
  - stage: checkfortemplateupdate
    displayName: Check for Template Update
    jobs:
      - job: checkfortemplateupdate
        timeoutInMinutes: 60
        displayName: Check for Template Update
        steps:
          - pwsh: |
              $Secrets = @("APPRISE_URL")
              $MissingSecret = $False
              foreach ($Secret in $Secrets) {
                if (!([Environment]::GetEnvironmentVariable($Secret)) -or ([Environment]::GetEnvironmentVariable($Secret) -eq "`$($Secret)")) {
                  Write-Host -Object "[error]Required Pipeline variable '$Secret' is not set! Please add it in Pipelines settings."
                  $MissingSecret = $True
                }
              }
              if ($MissingSecret) {
                throw "Erroring as one or more required secrets are missing!"
              }
            env:
              APPRISE_URL: $(APPRISE_URL)
            displayName: Validate Secrets Exist
          - checkout: self
            fetchDepth: 0
            persistCredentials: true
          - bash: |
              # renovate: datasource=github-releases depName=jdx/mise
              curl https://mise.run | MISE_VERSION=v2026.8.10 MISE_INSTALL_SKIP_IF_EXISTS=1 sh
              echo "##vso[task.prependpath]$(HOME)/.local/share/mise/bin"
              echo "##vso[task.prependpath]$(HOME)/.local/share/mise/shims"
            displayName: Install Mise
          - bash: mise install
            displayName: Run 'mise install'
          - pwsh: |
              [string]$CheckUpdateOutput = mise x -- copier check-update --output-format json --answers-file .config/copier-answers.yml
              $UpdateData = ConvertFrom-Json -InputObject $CheckUpdateOutput
              if ($UpdateData.update_available) {
                Write-Host -Object "Update available! Current version is $($UpdateData.current_version), latest version is $($UpdateData.latest_version)."
                apprise -i html -t "[$env:BUILD_REPOSITORY_NAME] Template Update Available" -b "Repository $env:BUILD_REPOSITORY_NAME has a new template update available.<br><br>Current version is $($UpdateData.current_version), latest version is $($UpdateData.latest_version)." $env:APPRISE_URL
              } else {
                Write-Host -Object "No update available."
              }
            env:
              APPRISE_URL: $(APPRISE_URL)
            displayName: Check for Template Updates
