name: $(BuildId)

trigger:
  branches:
    exclude:
      - "*"

schedules:
  - cron: 0 2 * * 1
    displayName: Run 'copier update' Every Monday at 2am
    branches:
      include:
        - main

variables:
  CI: true
  MISE_ENV: ci

pool:
  vmImage: ubuntu-latest

stages:
  - stage: checkfortemplateupdate
    displayName: Check for Template Update
    jobs:
      - job: checkfortemplateupdate
        timeoutInMinutes: 60
        displayName: Check for Template Update
        steps:
          - pwsh: |
              $Secrets = @("APPRISE_URL")
              $MissingSecret = $False
              foreach ($Secret in $Secrets) {
                if (!([Environment]::GetEnvironmentVariable($Secret)) -or ([Environment]::GetEnvironmentVariable($Secret) -eq "`$($Secret)")) {
                  Write-Host -Object "[error]Required Actions secret '$Secret' is not set! Please add it in Pipelines settings."
                  $MissingSecret = $True
                }
              }
              if ($MissingSecret) {
                throw "Erroring as one or more required secrets are missing!"
              }
            env:
              APPRISE_URI: $(APPRISE_URL)
            displayName: Validate Secrets Exist
          - checkout: self
            fetchDepth: 0
            persistCredentials: true
          - bash: |
              curl https://mise.run | sh
              echo "##vso[task.prependpath]$(HOME)/.local/share/mise/bin"
              echo "##vso[task.prependpath]$(HOME)/.local/share/mise/shims"
            displayName: Install Mise
          - bash: mise install
            displayName: Run 'mise install'
          - pwsh: |
              $CheckUpdateOutput = copier check-update --output-format json --answers-file .config/copier-answers.yml
              $UpdateData = ConvertFrom-Json -InputObject $CheckUpdateOutput
              if ($UpdateData.update_available) {
                apprise -i html -t "[$env:BUILD_REPOSITORY_NAME] Template Update Available" -b "Repository $env:BUILD_REPOSITORY_NAME has a new template update available.<br><br>Current version is $($UpdateData.current_version), latest version is $($UpdateData.latest_version)." $env:APPRISE_URL
              }
            env:
              APPRISE_URI: $(APPRISE_URI)
            displayName: Check for Template Updates
