name: Copier Source Template Update

on:
  schedule:
    - cron: 0 2 * * 1 # Every Monday at 2am
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Copier & Dependencies
        run: pip install -r .devcontainer/library/requirements.txt
      - name: Get New Template Version
        id: get_ver
        shell: pwsh
        run: |
          $Output = copier update -A -n --trust 2>&1
          $NewVersion = $Output[0].ToString().Split(" ")[-1]
          echo "NEW_VERSION=$NewVersion" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Run Copier Update
        run: |
          copier update --skip-answered --trust
          git add .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: copier update to parent template v${{ steps.get_ver.outputs.NEW_VERSION }}"
          branch: "copier-template-update-v${{ steps.get_ver.outputs.NEW_VERSION }}"
          delete-branch: true
          title: "feat: copier update to parent template v${{ steps.get_ver.outputs.NEW_VERSION }}"
          body: |
            Copier has applied updates from parent template v${{ steps.get_ver.outputs.NEW_VERSION }}.

            Review and push any needed changes to the `copier-template-update-v${{ steps.get_ver.outputs.NEW_VERSION }}` branch.
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
