name: "[Maint] Copier Update Check"

on:
  schedule:
    - cron: 0 17 * * 1 # Every Monday at 5pm UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  copier-check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secrets Exist
        shell: pwsh
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
        run: |
          $Secrets = @("APPRISE_URL")
          $MissingSecret = $False
          foreach ($Secret in $Secrets) {
            if (!([Environment]::GetEnvironmentVariable($Secret))) {
              Write-Host -Object "::error title=Missing Secret::Required Actions secret '$Secret' is not set! Please add it in repo/org settings."
              $MissingSecret = $True
            }
          }
          if ($MissingSecret) {
            throw "Erroring as one or more required secrets are missing!"
          }
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Ensures tags are checked out
      - name: Check for Copier Template Updates
        id: copier
        uses: natescherer/copier-action@v0
        with:
          subcommand: check-update
      - name: Notify if Update is Available
        if: steps.copier.outputs.check-update_update_available == 'true'
        uses: cstuder/apprise-ga@v3.1.0
        with:
          title: ${{ github.repository }} Template Update Available
          message: |
            Repository ${{ github.repository }} has a new template update available.

            Current version is ${{ steps.copier.outputs.check-update_current_version }}, latest version is ${{ steps.copier.outputs.check-update_latest_version }}.
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
