name: "Maint (Auto): Copier Update Check"

on:
  schedule:
    - cron: 0 17 * * 1 # Every Monday at 5pm UTC
  workflow_dispatch:

jobs:
  copier-check-update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0 # Ensures tags are checked out
      - name: Validate Secrets Exist
        uses: ./.github/actions/require-secrets
        with:
          secrets: |
            APPRISE_URL=${{ secrets.APPRISE_URL }}
      - name: Check for Copier Template Updates
        id: copier
        uses: natescherer/copier-action@b1ee418e5ee2e4334fc26094b9e84be3b93112ac # v0
        with:
          subcommand: check-update
      - name: Notify if Update is Available
        if: steps.copier.outputs.check-update_update_available == 'true'
        uses: cstuder/apprise-ga@bf5b5984a6017b3aea5c277da593839a0cdd2368 # v3.1.0
        with:
          title: ${{ github.repository }} Template Update Available
          message: |
            Repository ${{ github.repository }} has a new template update available.

            Current version is ${{ steps.copier.outputs.check-update_current_version }}, latest version is ${{ steps.copier.outputs.check-update_latest_version }}.
        env:
          APPRISE_URL: ${{ secrets.APPRISE_URL }}
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@f72ff1a1336129f29bf0166c0fd0ca6cf1bcb38c # v1
