name: "[Maint] Release Please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Validate Secrets Exist
        uses: ./.github/actions/require-secrets
        with:
          secrets: |
            REPO_MAINTENANCE_PAT=${{ secrets.REPO_MAINTENANCE_PAT }}
      - uses: googleapis/release-please-action@0dfd8538845b8e92600d271a895a5372865d4062 # v5
        with:
          token: ${{ secrets.REPO_MAINTENANCE_PAT }}
          config-file: .config/release-please-config.json
          manifest-file: .config/release-please-manifest.json
