name: "[Maint] Publish Release"

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release-on-knope-pr-merge:
    if: github.head_ref == 'knope/release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: knope-dev/action@19617851f9f13ab2f27a05989c55efb18aca3675 # v2.1.2
        with:
          version: 0.23.0
      - name: Publish Release
        run: knope release-on-knope-pr-merge --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
