name: "[Maint] Prepare Release PR"

on:
  push:
    branches: [main]

jobs:
  autoupdate-knope-pr:
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email github-actions@github.com
      - uses: knope-dev/action@19617851f9f13ab2f27a05989c55efb18aca3675 # v2.1.2
        with:
          version: 0.23.0
      - name: Prepare Release PR
        run: knope autoupdate-knope-pr --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
