name: "Release (Auto): Publish Release"

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  release-on-knope-pr-merge:
    if: github.head_ref == 'knope/release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4
      - name: Publish Release
        shell: bash
        run: mise x -- knope release-on-knope-pr-merge --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
