name: "Release (Auto): Prepare Release PR"

on:
  push:
    branches: [main]

jobs:
  autoupdate-knope-pr:
    if: "!contains(github.event.head_commit.message, 'chore: prepare release')"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email github-actions@github.com
      - uses: jdx/mise-action@3c2e0cf82a5b2e5249f0d3635a4d83d0ae861518 # v4
      - name: Prepare Release PR
        shell: bash
        run: mise x -- knope autoupdate-knope-pr --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
