name: "Tests: PR Tests"

on:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: hk check
        run: hk check --from-ref main
      - name: Example Tests
        run: |
          FILE=README.md
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
            echo "Also you should probably put one or more real checks relevant to your project here."
          else
            echo "$FILE missing!"
            exit 1
          fi
