extends: default

rules:
  anchors:
    forbid-unused-anchors: true
<<<<<<< before updating
  comments:
    min-spaces-from-content: 1
=======
>>>>>>> after updating
  document-start: disable
  empty-values:
    ignore:
      - "**/workflows/*.yml"
      - "**/workflows/*.yml{% endif %}"
  indentation:
    spaces: 2
    check-multi-line-strings: true
    ignore:
<<<<<<< before updating
      - "**/workflows/*.yml"
      - "**/workflows/*.yml{% endif %}"
      - "**/*.azurepipelines*/*.yml"
=======
      - "**/workflows/*.yml.*"
      - "**/workflows/*.yml{% endif %}"
      - "**/*.azurepipelines*/*.yml.*"
>>>>>>> after updating
      - "**/*.azurepipelines*/*.yml{% endif %}"
  line-length: disable
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  truthy:
    ignore:
<<<<<<< before updating
      - "**/workflows/*.yml"
      - "**/workflows/*.yml{% endif %}"
=======
      - "**/workflows/*.yml.*"
      - "**/workflows/*.yml{% endif %}"
>>>>>>> after updating
