exclude = [
    '.*%7B.*%7D.*', # Python f-strings
    'https://img\.shields\.io/github/all-contributors/', # Part of template code
    'https://dev.azure.com', # This errors frequently, easier to just ignore
    'https://github\.com/natescherer/postmodern-repo-copiertemplate/compare/v0\.0\.1\.\.\.v0\.2\.0'
]
exclude_path = [
    ".config/lychee.toml",
    ".config/typos.toml",
    "template/.config/lychee.toml.jinja"
]