[global]
disable = [
  "MD013", # Disable line length checking
  "MD046", # Disable code block style (Zensical)
  "MD057", # Disable link checking in favor of Lychee
]

[MD007]
indent = 4 # Set list indentation to 4 spaces

[MD077]
indent = 4 # Set the indent for unordered list items to 4 spaces (Zensical)
