[default]
extend-ignore-re = [
  '\(\[.*\]\(https:\/\/github\.com\/.*\)\)', # CHANGELOG.md links
]

[default.extend-words]
# Author Name Components
Nate = "Nate"
Scherer = "Scherer"
# GitHub Username
natescherer = "natescherer"
# Repo Name
postmodern-repo-copiertemplate = "postmodern-repo-copiertemplate"
# Custom Words Below
