[tasks.test_integration_gh]
run = '''
copier copy --trust --vcs-ref={{option(name="branch",default="HEAD")}} -d 'developer_platform=GitHub' -d 'github_repo_description=Integration Test - NOT FOR PUBLIC USE' -d 'project_type=Template' -d 'project_name=Integration Test' -d 'project_visibility=Public' -d 'license=MIT' -d 'lifecycle=Pre-Alpha' https://github.com/natescherer/postmodern-repo-copiertemplate {{option(name="path")}}
'''

[tasks.test_integration_azdo]
run = '''
copier copy --trust --vcs-ref={{option(name="branch",default="HEAD")}} -d 'developer_platform=Azure DevOps' -d 'azdo_org=natescherer' -d 'azdo_project=natescherer' -d 'project_type=Template' -d 'project_name=Integration Test' -d 'project_visibility=Private' -d 'license=None' -d 'lifecycle=Pre-Alpha' https://github.com/natescherer/postmodern-repo-copiertemplate {{option(name="path")}}
'''
