name: All Contributors PR Create

on:
  push:
    branches:
      - main

permissions:
    issues: write
    pull-requests: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run All Contributors Auto Action
        uses: JoshuaKGoldberg/all-contributors-auto-action@v0.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}