name: "[Maint] Copier Update Check"

on:
  schedule:
    - cron: 0 17 * * 1 # Every Monday at 5pm UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  MISE_ENV: ci

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secrets Exist
        shell: pwsh
        env:
          APPRISE_URI: ${{ secrets.APPRISE_URI }}
        run: |
          $Secrets = @("APPRISE_URI")
          $MissingSecret = $False
          foreach ($Secret in $Secrets) {
            if (!([Environment]::GetEnvironmentVariable($Secret))) {
              Write-Host -Object "::error title=Missing Secret::Required Actions secret '$Secret' is not set! Please add it in repo/org settings."
              $MissingSecret = $True
            }
          }
          if ($MissingSecret) {
            throw "Erroring as one or more required secrets are missing!"
          }
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Check for Template Updates
        shell: pwsh
        env:
          APPRISE_URI: ${{ secrets.APPRISE_URI }}
        run: |
          $CurrentVersion = $(yq '._commit' .config/copier-answers.yml).TrimStart("v")
          $Output = copier update --answers-file .config/copier-answers.yml --skip-answered --pretend --trust 2>&1
          $NewVersion = $Output[0].ToString().Split(" ")[-1]
          if ([System.Version]$CurrentVersion -lt [System.Version]$NewVersion) {
            apprise -i html -t "[${{ github.repository }}] Template Update Available" -b "Current Version: <i>$CurrentVersion</i> New Version: <i>$NewVersion</i><br><br>Run <b>mise run copier-update</b> to update." $env:APPRISE_URI
          }
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
