name: "[Maint] MkDocs Publish to GitHub Pages"

on:
  push:
    branches:
      - main
    paths:
      - .config/mkdocs/**
      - docs/**
  release:
    types:
      - published

permissions:
  contents: write
  pages: write
  id-token: write

env:
  MISE_ENV: ci

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - uses: jiangxin/file-exists-action@v1
        id: index-check
        with:
          path: index.html
          ref: gh-pages
      - run: mike set-default -F .config/mkdocs/mkdocs.yml --push --allow-undefined dev
        if: ${{ steps.index-check.outputs.exists == 'false' }}
      - run: mike deploy -F .config/mkdocs/mkdocs.yml --push --update-aliases dev
        if: ${{ github.event_name == 'push' }}
      - run: |
          mike deploy -F .config/mkdocs/mkdocs.yml --push --update-aliases ${{ github.event.release.tag_name }} latest
          mike set-default -F .config/mkdocs/mkdocs.yml --push latest
        if: ${{ github.event_name == 'release' }}
  deploy-mkdocs:
    needs: build-mkdocs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
