name: "[Maint] Release Please"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Secrets Exist
        shell: pwsh
        env:
          REPO_MAINTENANCE_PAT: ${{ secrets.REPO_MAINTENANCE_PAT }}
        run: |
          $Secrets = @("REPO_MAINTENANCE_PAT")
          $MissingSecret = $False
          foreach ($Secret in $Secrets) {
            if (!([Environment]::GetEnvironmentVariable($Secret))) {
              Write-Host -Object "::error title=Missing Secret::Required Actions secret '$Secret' is not set! Please add it in repo/org settings."
              $MissingSecret = $True
            }
          }
          if ($MissingSecret) {
            throw "Erroring as one or more required secrets are missing!"
          }
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.REPO_MAINTENANCE_PAT }}
          config-file: .config/release-please-config.json
          manifest-file: .config/release-please-manifest.json
